export const endpoints = {
  authLogin: '/api/auth/login',
  authRefresh: '/api/auth/refresh',
  authLogout: '/api/auth/logout',
  authGoogleLogin: '/api/auth/google-login',
  authRegister: '/api/auth/register',
  authForgotPassword: '/api/auth/forgot-password',
  careerGoals: '/api/career-goals',
  assessments: '/api/assessments',
  assessmentsMe: '/api/assessments/me',
  recommendations: '/api/recommendations',
  learningPathById: (id: string) => `/api/learning-paths/${id}`,
  learningPathModulesById: (id: string) => `/api/learning-paths/${id}/modules`,
  learningPathProgress: (id: string) => `/api/learning-paths/${id}/progress`,
  badges: '/api/badges',
  industryTrends: '/api/industry-trends',
  companyCandidates: '/api/company/candidates',
  jobRecommendations: '/api/jobs/recommendations',
  companyJobs: '/api/company/jobs',
  companyJobById: (id: string) => `/api/company/jobs/${id}`,
  progressSummaryByPath: (learningPathId: string) => `/api/progress/${learningPathId}`,
  userProfile: '/api/user/profile',
  skills: '/api/skills',
} as const
